### ISSUE TITLE
Windows Issue

### ISSUE THREAD

**Issue by igorpereirabr1** [Methexis-Inc/terminal-copilot#17]
Looks like the dependency of simple-term-menu package makes impossible to use this in Windows: https://github.com/IngoMeyer441/simple-term-menu/issues/71

Traceback (most recent call last):
  File "C:\Users\ju195\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ju195\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ju195\Anaconda3\Scripts\copilot.exe\__main__.py", line 4, in <module>       
  File "C:\Users\ju195\Anaconda3\lib\site-packages\copilot\copilot.py", line 8, in <module>
    from simple_term_menu import TerminalMenu
  File "C:\Users\ju195\Anaconda3\lib\site-packages\simple_term_menu.py", line 39, in <module>
    raise NotImplementedError('"{}" is currently not supported.'.format(platform.system())) from e
NotImplementedError: "Windows" is currently not supported.

**Comment by JoelKronander** [comment]
Ah thanks for noting that.

Would you be up for making a pr that detects if the user runs windows and does a different import/type of menu selection? I don't have a windows machine so hard to test for me.

**Comment by JoelKronander** [comment]
Fixed by @EdwardTheLegend! ❤️
Let us know if something still don't work as expected on Windows.
