### ISSUE TITLE
can't work with me, i get error

### ISSUE THREAD

**Issue by ahmeteid7** [Methexis-Inc/terminal-copilot#54]
```
copilot -q "What is the best drink for late night coding?"
Traceback (most recent call last):
  File "/home/eid/.local/bin/copilot", line 5, in <module>
    from copilot.main import main
  File "/home/eid/.local/lib/python3.8/site-packages/copilot/main.py", line 12, in <module>
    from copilot.conversation import Conversation
  File "/home/eid/.local/lib/python3.8/site-packages/copilot/conversation.py", line 20, in <module>
    class Conversation:
  File "/home/eid/.local/lib/python3.8/site-packages/copilot/conversation.py", line 21, in Conversation
    messages: list[dict]
TypeError: 'type' object is not subscriptable

```

**Comment by ahmeteid7** [comment]
??
